{
Author Prof1983 <prof1983@ya.ru>
Created 05.02.2013
LastMod 05.02.2013
}

const
  SFieldIn = 'FieldsIn не задано';
  SFieldOut = 'FieldsOut не задано';
  SKeyFieldsIn = 'KeyFieldsIn не задано';
  SKeyFieldsOut = 'KeyFieldsOut не задано';
  SFieldsCount = ' олличество полей в FieldsIn и FieldsOut не одинаковое';
  SKeyFieldsCount = ' олличество ключевых полей дл€ сравнени€ в KeyFieldsIn и KeyFieldsOut не одинаковое';
  SFieldInError = 'ѕоле %s присутствует в списке ключевых полей и полей дл€ обновлени€ внутренней таблици %s';
  SFieldOutError = 'ѕоле %s присутствует в списке ключевых полей и полей дл€ обновлени€ внешней таблици %s';
