{**
@Abstract User Interface exports
@Author Prof1983 <prof1983@ya.ru>
@Created 28.04.2011
@LastMod 28.03.2013
}
unit AUiExp;

interface

uses
  AUiAboutDialog,
  AUiBox,
  AUiButtons,
  AUiCalendar,
  AUiCalendarDialog,
  AUiCheckBox,
  AUiComboBox,
  AUiControls,
  AUiControlsA,
  AUiDataSource,
  AUiDialogs,
  AUiDialogsEx1,
  AUiDialogsEx2,
  AUiEdit,
  AUiErrorDialog,
  AUiEvents,
  AUiFilterDialog,
  AUiGrids,
  AUiImages,
  AUiInit,
  AUiLabels,
  AUiLabelsEx,
  AUiListBox,
  AUiMain,
  AUiMainWindow,
  AUiMainWindow2,
  AUiMenus,
  AUiPageControl,
  AUiProgressBar,
  AUiPropertyBox,
  AUiReports,
  AUiSpin,
  AUiSpinEdit,
  AUiSplitter,
  AUiTextView,
  AUiToolBar,
  AUiToolMenu,
  AUiTrayIcon,
  AUiTreeView,
  AUiWaitWin,
  AUiWindows,
  AUiWindowSettings;

exports
  AUi_CreateMainForm,
  AUi_ExecuteAboutDialog,
  AUi_ExecuteCalendarDialog,
  AUi_ExecuteColorDialog,
  AUi_ExecuteDateFilterDialog,
  AUi_ExecuteErrorDialog,
  AUi_ExecuteErrorDialogA,
  AUi_ExecuteFontDialog,
  AUi_ExecuteFontDialogA,
  AUi_ExecuteInputBox1,
  AUi_ExecuteInputBox1A,
  AUi_ExecuteInputBox2,
  AUi_ExecuteInputBox2A,
  AUi_ExecuteLoginDialog,
  AUi_ExecuteMessageDialog1,
  AUi_ExecuteMessageDialog1A,
  AUi_ExecuteOpenFileDialog,
  AUi_ExecutePrinterSetupDialog,
  AUi_ExecuteSaveFileDialog1,
  AUi_Fin,
  AUi_GetIsShowApp,
  AUi_GetMainMenuItem,
  AUi_GetMainToolBar,
  AUi_GetMainTrayIcon,
  AUi_GetMainWindow,
  AUi_Init,
  AUi_InitAboutDialogWin2,
  AUi_InitMainTrayIcon,
  AUi_InitMenus,
  AUi_OnDone_Connect,
  AUi_OnDone_Disconnect,
  AUi_ProcessMessages,
  AUi_Run,
  AUi_SetAboutMemoDefaultSize,
  AUi_SetHideOnClose,
  AUi_SetIsShowApp,
  AUi_SetMainToolBar,
  AUi_SetMainWindow,
  AUi_SetMainWindow2,
  AUi_SetOnAboutClick,
  AUi_SetOnMainFormCreate,
  AUi_SetProgramState,
  AUi_ShellExecute,
  AUi_ShellExecuteA,
  AUi_ShowHelp,
  AUi_ShowHelp2,
  AUi_Shutdown,

  AUiAboutDialog_Init2,
  AUiAboutDialog_New,

  AUiBox_New,

  AUiButton_New,
  AUiButton_SetKind,

  AUiCalendar_GetDate,
  AUiCalendar_New,
  AUiCalendar_SetMonth,

  AUiCheckBox_Free,
  AUiCheckBox_GetChecked,
  AUiCheckBox_New,
  AUiCheckBox_NewEx,
  AUiCheckBox_SetChecked,

  AUiComboBox_Add,
  AUiComboBox_AddA,
  AUiComboBox_GetItemIndex,
  AUiComboBox_New,
  AUiComboBox_New2,
  AUiComboBox_SetItemIndex,

  AUiControl_Free,
  AUiControl_FreeAndNil,
  AUiControl_GetClientHeight,
  AUiControl_GetClientWidth,
  AUiControl_GetColor,
  AUiControl_GetEnabled,
  AUiControl_GetHeight,
  AUiControl_GetHint,
  AUiControl_GetHintA,
  AUiControl_GetMenu,
  AUiControl_GetName,
  AUiControl_GetNameA,
  AUiControl_GetPosition,
  AUiControl_GetText,
  AUiControl_GetTop,
  AUiControl_GetVisible,
  AUiControl_GetWidth,
  AUiControl_SetAlign,
  AUiControl_SetAnchors,
  AUiControl_SetBevel,
  AUiControl_SetClientSize,
  AUiControl_SetColor,
  AUiControl_SetCursor,
  AUiControl_SetEnabled,
  AUiControl_SetFocus,
  AUiControl_SetFont1A,
  AUiControl_SetFontColor,
  AUiControl_SetFontSize,
  AUiControl_SetFontStyle,
  AUiControl_SetHeight,
  AUiControl_SetHint,
  AUiControl_SetHintA,
  AUiControl_SetName,
  AUiControl_SetNameA,
  AUiControl_SetOnChange,
  AUiControl_SetOnChangeEx,
  AUiControl_SetOnClick,
  AUiControl_SetPosition,
  AUiControl_SetSize,
  AUiControl_SetTabStop,
  AUiControl_SetText,
  AUiControl_SetTextA,
  AUiControl_SetTop,
  AUiControl_SetVisible,
  AUiControl_SetWidth,

  AUiDataSource_New,
  AUiDataSource_SetOnDataChange,

  AUiDialog_AddButton1,
  AUiDialog_Free,
  AUiDialog_GetButtonsBox,
  AUiDialog_GetWindow,
  AUiDialog_New,
  AUiDialog_ShowModal,

  AUiEdit_CheckDate,
  AUiEdit_CheckFloat,
  AUiEdit_CheckFloat32,
  AUiEdit_CheckFloat64,
  AUiEdit_CheckInt,
  AUiEdit_New,
  AUiEdit_NewEx,

  AUiGrid_AddColumn,
  AUiGrid_Clear,
  AUiGrid_Clear2,
  AUiGrid_DeleteRow,
  AUiGrid_DeleteRow2,
  AUiGrid_FindInt,
  AUiGrid_New,
  AUiGrid_RestoreColProps,
  AUiGrid_RestoreColPropsA,
  AUiGrid_RowDown,
  AUiGrid_RowUp,
  AUiGrid_SaveColProps,
  AUiGrid_SaveColPropsA,
  AUiGrid_SetColumnWidth,
  AUiGrid_SetColumnWidth2,
  AUiGrid_SetDataSource,
  AUiGrid_SetRowCount,

  AUiImage_LoadFromFile,
  AUiImage_LoadFromFileA,
  AUiImage_New,
  AUiImage_SetCenter,
  AUiImage_SetTransparent,

  AUiLabel_New,
  AUiLabel_New2,
  AUiLabel_SetAlignment,
  AUiLabel_SetAutoSize,
  AUiLabel_SetWordWrap,

  AUiListBox_Add,
  AUiListBox_Clear,
  AUiListBox_DeleteItem,
  AUiListBox_GetCount,
  AUiListBox_GetItem,
  AUiListBox_GetItemIndex,
  AUiListBox_New,
  AUiListBox_New2,
  AUiListBox_SetChecked,
  AUiListBox_SetItem,
  AUiListBox_SetItemHeight,
  AUiListBox_SetItemIndex,
  AUiListBox_SetOnDblClick,

  AUiMainWindow_AddMenuItem,
  AUiMainWindow_AddMenuItemA,
  AUiMainWindow_GetLeftContainer,
  AUiMainWindow_GetMainContainer,
  AUiMainWindow_GetRightContainer,

  AUiMenu_AddItem0,
  AUiMenu_AddItem1,
  AUiMenu_AddItem2,
  AUiMenu_AddItem3,
  AUiMenu_Clear,
  AUiMenu_FindItemByName,
  AUiMenu_GetItems,
  AUiMenu_New,
  AUiMenu_New2,
  AUiMenu_SetChecked,

  AUiPageControl_AddPage,
  AUiPageControl_AddPageA,
  AUiPageControl_New,

  AUiProgressBar_New,
  AUiProgressBar_SetMaxPosition,
  AUiProgressBar_SetPosition,
  AUiProgressBar_StepBy,
  AUiProgressBar_StepIt,

  AUiPropertyBox_Add,
  AUiPropertyBox_Add2,
  AUiPropertyBox_GetUseBigFont,
  AUiPropertyBox_Item_GetValue,
  AUiPropertyBox_Item_SetValue,
  AUiPropertyBox_New,
  AUiPropertyBox_SetIsAppPoints,
  AUiPropertyBox_SetUseBigFont,

  AUiReport_New,
  AUiReport_SetText,

  AUiReportWin_New,
  AUiReportWin_New2,
  AUiReportWin_ShowReport,

  AUiSpinButton_New,

  AUiSpinEdit_GetValue,
  AUiSpinEdit_New,
  AUiSpinEdit_NewEx,
  AUiSpinEdit_SetValue,

  AUiSplitter_New,

  AUiTextView_AddLine,
  AUiTextView_New,
  AUiTextView_SetFont,
  AUiTextView_SetReadOnly,
  AUiTextView_SetScrollBars,
  AUiTextView_SetWordWrap,

  AUiToolBar_AddButton,
  AUiToolBar_AddButton1,
  AUiToolBar_New,

  AUiToolMenu_AddNewItem,
  AUiToolMenu_AddNewSubMenu,
  AUiToolMenu_GetSubMenu,
  AUiToolMenu_New,

  AUiTrayIcon_Free,
  AUiTrayIcon_GetHint,
  AUiTrayIcon_GetMenuItems,
  AUiTrayIcon_GetPopupMenu,
  AUiTrayIcon_New,
  AUiTrayIcon_SetHint,
  AUiTrayIcon_SetIcon,
  AUiTrayIcon_SetIsActive,
  AUiTrayIcon_SetOnLeftClick,
  AUiTrayIcon_SetOnRightClick,
  AUiTrayIcon_SetPopupMenu,

  AUiTreeView_AddItem,
  AUiTreeView_New,

  AUiWaitWin_New,
  AUiWaitWin_SetMaxPosition,
  AUiWaitWin_SetPosition,
  AUiWaitWin_SetText,
  AUiWaitWin_StepBy,

  AUiWindow_Add,
  AUiWindow_Free,
  AUiWindow_FreeAndNil,
  AUiWindow_GetMenu,
  AUiWindow_LoadConfig,
  AUiWindow_LoadConfig2,
  AUiWindow_New,
  AUiWindow_SaveConfig,
  AUiWindow_SaveConfig2,
  AUiWindow_SetBorderStyle,
  AUiWindow_SetFormStyle,
  AUiWindow_SetPosition,
  AUiWindow_SetState,
  AUiWindow_ShowModal,
  AUiWindow_ShowModal2;

implementation

end.
